namespace: "ansible_fact"
name: "os_facts"
version: "0.0.1"
readme: "docs/README.md"
authors:
  - "Andrew J. Huffman (https://github.com/ahuffman)"
  - "John Westcott IV (https://github.com/john-westcott-iv)"
description: "ansible-fact consists of a collection of custom Ansible fact collectors to generate structured data and harvest system configurations to provide infrastructure-as-code in reverse."
license: "GPL-3.0-or-later"
#license_file: ""
issues: "https://github.com/ahuffman/ansible-fact/issues"
tags:
  - "fact"
  - "facts"
  - "users"
  - "user"
  - "groups"
  - "group"
  - "sudo"
  - "sudoers"
  - "cron"
  - "anacron"
  - "yum"
  - "repositories"
  - "repository"
  - "procs"
  - "processes"
  - "process"
  - "iac"
dependencies: {}
repository: "https://github.com/ahuffman/ansible-fact"
documentation: "https://github.com/ahuffman/ansible-fact"
homepage: "https://github.com/ahuffman/ansible-fact/issues"
