language: python
branches:
  only:
    - dev
services:
  - docker

install: skip
before_script:
  # prep Ubuntu VM
  - pip install ansible jmespath
  - sudo apt-get update
  - sudo apt-get install -y acl
  ### ensure root owns as there is no travis user/group in containers (uid:2000)
  - sudo chown -R root.root ../ansible-fact
  # prep containers
  - docker pull ahuffman/afbullseye:latest
  - docker pull ahuffman/afcentos7:latest
  - cd ../
  - pwd
  # fire up the pre-built testing Ansible containers
  ## container Dockerfile's are found here: https://github.com/ahuffman/ansible-fact-testing-containers
  - docker run -it --name bullseye -d -v `pwd`/ansible-fact:/home/travis/build/ahuffman/ansible-fact:z ahuffman/afbullseye:latest /bin/bash
  - docker run -it --name centos7 -d -v `pwd`/ansible-fact:/home/travis/build/ahuffman/ansible-fact:z ahuffman/afcentos7:latest /bin/bash

script:
  - /home/travis/build/ahuffman/ansible-fact/os_facts/tests/travis-script.sh
