language: python
branches:
  only:
    - dev
services:
  - docker

install: skip
before_script:
  # prep Ubuntu VM
  - pip install ansible
  # prep containers
  - docker pull debian:bullseye
  - docker pull centos:centos7
  - cd ../
  - pwd
  # fire up the containers
  - docker run -it --name bullseye -d -v `pwd`/ansible-fact:/home/travis/build/ahuffman/ansible-fact:z debian:bullseye /bin/bash
  - docker run -it --name centos7 -d -v `pwd`/ansible-fact:/home/travis/build/ahuffman/ansible-fact:z centos:centos7 /bin/bash
  # install what we need on containers
  ## Debian Bullseye:
  - docker exec -it bullseye apt-get update
  - docker exec -it bullseye apt-get install -y python-pip
  - docker exec -it bullseye pip install ansible
  - docker exec -it bullseye /bin/bash -c 'export PATH=$PATH:/usr/local/bin'
  ## CentOS7:
  - docker exec -it centos7 yum install -y epel-release centos-release-scl
  - docker exec -it centos7 yum install -y ansible # scl-utils rh-python36-python
# for testing 3.x python (need to move this somewhere else later - let's get basics working 1st)
#  - scl enable rh-python36 bash && yum install -y ansible
script:
  # Run tests on Ubuntu VM
  - echo "Ubuntu VM info:"
  - cat /etc/os-release
  - uname -a
  - echo "Test Ubuntu:"
  - /home/travis/build/ahuffman/ansible-fact/os_facts/tests/travis-script.sh
  # Run tests on Debian Bullseye
  - echo "Debian Bullseye container info:"
  - docker inspect bullseye
  - echo "Test Debian Bullseye:"
  - docker exec -it bullseye /home/travis/build/ahuffman/ansible-fact/os_facts/tests/travis-script.sh
  # Run tests on CentOS7
  - echo "CentOS7 container info:"
  - docker inspect centos7
  - echo "Test CentOS7:"
  - docker exec -it centos7 /home/travis/build/ahuffman/ansible-fact/os_facts/tests/travis-script.sh
