language: python
branches:
  only:
    - dev
services:
  - docker

install: skip
before_script:
  - docker pull centos:centos7
  - cd ../
  - pwd
  - docker run -it --name centos7 -d -v `pwd`/ansible-fact:/root/ansible-fact centos:centos7 /bin/bash
  # get container info
  - docker inspect centos7
  - docker exec -it centos7 yum install -y epel-release centos-release-scl
  - docker exec -it centos7 yum install -y ansible # scl-utils rh-python36-python
# for testing 3.x python (need to move this somewhere else later - let's get basics working 1st)
#  - scl enable rh-python36 bash && yum install -y ansible

script:
  - docker exec -it centos7 /root/ansible-fact/test/travis-script.sh
